include:
  - project: 'swepy/cicd-templates/ruff'
    ref: 'ruff@1.0.2'
    file: 'ruff.yaml'

stages:
  - format
  - lint
  - build
  - test
  - deploy

format-job:
  stage: format
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff format

lint-job:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff check --fix
    - ruff check --output-format=gitlab .
  needs:
    - format
  

build-job:
  stage: build
  image: docker:latest
  script:
    - docker build -t avatar:$CI_COMMIT_SHORT_SHA .
  needs:
    - lint

test-job:
  stage: test
  image: docker:latest
  script:
    - docker run -t -d avatar:$CI_COMMIT_SHORT_SHA
    - docker exec -i -t avatar:$CI_COMMIT_SHORT_SHA sh
    - python -m pytest test/*.py
  
deploy-job:
  stage: deploy
  image: docker:latest
  needs:
    - test
  script:
    - echo $DOCKER_ACCESS_TOKEN | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_REGISTRY/nrlp/avatar/avatar:$CI_COMMIT_SHORT_SHA
